version: '3.2'

services:
  ms-gateway:
    image: zhomt/msgateway:latest
    environment:
      MS_BACKEND_URI: ms-backend
    ports:
      - '80:80'

  ms-backend:
    image: zhomt/msbackend:latest
    ports:
      - '8080:8080'
    environment:
      MONGO_HOST: ms-mongodb
      MONGO_PORT: 27017

  ms-mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
