version: '2.0.2'

services:

  ms-postgres:
    image: postgres:13.4
    container_name: ms-postgres
    environment:
      POSTGRES_DB: ms-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: postgres -c listen_addresses=*
    ports:
        - '3306:5432'
