version: '2.0.2'

services:

  ms-mongodb:
    image: mongo:latest
    container_name: ms-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
