version: '3.2'

services:
  ms-gateway:
    image: zhomt/msgateway:latest
    ports:
      - '80:80'
    networks:
      - ms_network
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 192M
      placement:
        constraints:
          - node.role != manager

  ms-backend:
    image: zhomt/msbackend:latest
    ports:
      - '8080:8080'
    environment:
      MONGO_HOST: ms-mongodb
      MONGO_PORT: 27017
    networks:
      - ms_network
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 192M
      placement:
        constraints:
          - node.role != manager

  ms-mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - ms_network
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
      placement:
        constraints: [node.hostname == database-01]

networks:
  ms_network:
    driver: overlay
    attachable: true